[package]
name = "soop"
version = "0.1.0"
edition = "2024"
authors = ["Jun Park <pj2417@gmail.com>"]
description = "SSH cOnfig OPerator"
license = "MIT"
repository = "https://github.com/currybab/soop"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
dialoguer = "0.12.0"
regex = "1.12.1"

[dev-dependencies]
rand = "0.8"
